package vaadin.scala.tests

import vaadin.scala.server.FontAwesome

/**
 *
 * @author Henri Kerola / Vaadin
 */
class FontAwesomeTests extends ScaladinTestSuite {

  ignore("generate constants") {
    com.vaadin.server.FontAwesome.values.foreach { v =>
      val scalaName = v.name().split("_").map(p => p.substring(0, 1).toUpperCase + p.substring(1).toLowerCase).mkString
      println("val " + scalaName + " = FontAwesome(" + v.name() + ")")
    }
  }

  test("All FontAwesome constants are defined") {
    FontAwesome.Adjust
    FontAwesome.Adn
    FontAwesome.AlignCenter
    FontAwesome.AlignJustify
    FontAwesome.AlignLeft
    FontAwesome.AlignRight
    FontAwesome.Ambulance
    FontAwesome.Anchor
    FontAwesome.Android
    FontAwesome.AngleDoubleDown
    FontAwesome.AngleDoubleLeft
    FontAwesome.AngleDoubleRight
    FontAwesome.AngleDoubleUp
    FontAwesome.AngleDown
    FontAwesome.AngleLeft
    FontAwesome.AngleRight
    FontAwesome.AngleUp
    FontAwesome.Apple
    FontAwesome.Archive
    FontAwesome.ArrowCircleDown
    FontAwesome.ArrowCircleLeft
    FontAwesome.ArrowCircleODown
    FontAwesome.ArrowCircleOLeft
    FontAwesome.ArrowCircleORight
    FontAwesome.ArrowCircleOUp
    FontAwesome.ArrowCircleRight
    FontAwesome.ArrowCircleUp
    FontAwesome.ArrowDown
    FontAwesome.ArrowLeft
    FontAwesome.ArrowRight
    FontAwesome.ArrowUp
    FontAwesome.Arrows
    FontAwesome.ArrowsAlt
    FontAwesome.ArrowsH
    FontAwesome.ArrowsV
    FontAwesome.Asterisk
    FontAwesome.Automobile
    FontAwesome.Backward
    FontAwesome.Ban
    FontAwesome.Bank
    FontAwesome.BarChartO
    FontAwesome.Barcode
    FontAwesome.Bars
    FontAwesome.Beer
    FontAwesome.Behance
    FontAwesome.BehanceSquare
    FontAwesome.Bell
    FontAwesome.BellO
    FontAwesome.Bitbucket
    FontAwesome.BitbucketSquare
    FontAwesome.Bitcoin
    FontAwesome.Bold
    FontAwesome.Bolt
    FontAwesome.Bomb
    FontAwesome.Book
    FontAwesome.Bookmark
    FontAwesome.BookmarkO
    FontAwesome.Briefcase
    FontAwesome.BTC
    FontAwesome.Bug
    FontAwesome.Building
    FontAwesome.BuildingO
    FontAwesome.Bullhorn
    FontAwesome.Bullseye
    FontAwesome.Cab
    FontAwesome.Calendar
    FontAwesome.CalendarO
    FontAwesome.Camera
    FontAwesome.CameraRetro
    FontAwesome.Car
    FontAwesome.CaretDown
    FontAwesome.CaretLeft
    FontAwesome.CaretRight
    FontAwesome.CaretSquareODown
    FontAwesome.CaretSquareOLeft
    FontAwesome.CaretSquareORight
    FontAwesome.CaretSquareOUp
    FontAwesome.CaretUp
    FontAwesome.Certificate
    FontAwesome.Chain
    FontAwesome.ChainBroken
    FontAwesome.Check
    FontAwesome.CheckCircle
    FontAwesome.CheckCircleO
    FontAwesome.CheckSquare
    FontAwesome.CheckSquareO
    FontAwesome.ChevronCircleDown
    FontAwesome.ChevronCircleLeft
    FontAwesome.ChevronCircleRight
    FontAwesome.ChevronCircleUp
    FontAwesome.ChevronDown
    FontAwesome.ChevronLeft
    FontAwesome.ChevronRight
    FontAwesome.ChevronUp
    FontAwesome.Child
    FontAwesome.Circle
    FontAwesome.CircleO
    FontAwesome.CircleONotch
    FontAwesome.CircleThin
    FontAwesome.Clipboard
    FontAwesome.ClockO
    FontAwesome.Cloud
    FontAwesome.CloudDownload
    FontAwesome.CloudUpload
    FontAwesome.Cny
    FontAwesome.Code
    FontAwesome.CodeFork
    FontAwesome.Codepen
    FontAwesome.Coffee
    FontAwesome.Cog
    FontAwesome.COGS
    FontAwesome.Columns
    FontAwesome.Comment
    FontAwesome.CommentO
    FontAwesome.Comments
    FontAwesome.CommentsO
    FontAwesome.Compass
    FontAwesome.Compress
    FontAwesome.Copy
    FontAwesome.CreditCard
    FontAwesome.Crop
    FontAwesome.Crosshairs
    FontAwesome.CSS3
    FontAwesome.Cube
    FontAwesome.Cubes
    FontAwesome.Cut
    FontAwesome.Cutlery
    FontAwesome.Dashboard
    FontAwesome.Database
    FontAwesome.Dedent
    FontAwesome.Delicious
    FontAwesome.Desktop
    FontAwesome.Deviantart
    FontAwesome.Digg
    FontAwesome.Dollar
    FontAwesome.DotCircleO
    FontAwesome.Download
    FontAwesome.Dribbble
    FontAwesome.Dropbox
    FontAwesome.Drupal
    FontAwesome.Edit
    FontAwesome.Eject
    FontAwesome.EllipsisH
    FontAwesome.EllipsisV
    FontAwesome.Empire
    FontAwesome.Envelope
    FontAwesome.EnvelopeO
    FontAwesome.EnvelopeSquare
    FontAwesome.Eraser
    FontAwesome.EUR
    FontAwesome.Euro
    FontAwesome.Exchange
    FontAwesome.Exclamation
    FontAwesome.ExclamationCircle
    FontAwesome.ExclamationTriangle
    FontAwesome.Expand
    FontAwesome.ExternalLink
    FontAwesome.ExternalLinkSquare
    FontAwesome.Eye
    FontAwesome.EyeSlash
    FontAwesome.Facebook
    FontAwesome.FacebookSquare
    FontAwesome.FastBackward
    FontAwesome.FastForward
    FontAwesome.Fax
    FontAwesome.Female
    FontAwesome.FighterJet
    FontAwesome.File
    FontAwesome.FileArchiveO
    FontAwesome.FileAudioO
    FontAwesome.FileCodeO
    FontAwesome.FileExcelO
    FontAwesome.FileImageO
    FontAwesome.FileMovieO
    FontAwesome.FileO
    FontAwesome.FilePdfO
    FontAwesome.FilePhotoO
    FontAwesome.FilePictureO
    FontAwesome.FilePowerpointO
    FontAwesome.FileSoundO
    FontAwesome.FileText
    FontAwesome.FileTextO
    FontAwesome.FileVideoO
    FontAwesome.FileWordO
    FontAwesome.FileZipO
    FontAwesome.FilesO
    FontAwesome.Film
    FontAwesome.Filter
    FontAwesome.Fire
    FontAwesome.FireExtinguisher
    FontAwesome.Flag
    FontAwesome.FlagCheckered
    FontAwesome.FlagO
    FontAwesome.Flash
    FontAwesome.Flask
    FontAwesome.Flickr
    FontAwesome.FloppyO
    FontAwesome.Folder
    FontAwesome.FolderO
    FontAwesome.FolderOpen
    FontAwesome.FolderOpenO
    FontAwesome.Font
    FontAwesome.Forward
    FontAwesome.Foursquare
    FontAwesome.FrownO
    FontAwesome.Gamepad
    FontAwesome.Gavel
    FontAwesome.GBP
    FontAwesome.Ge
    FontAwesome.Gear
    FontAwesome.Gears
    FontAwesome.Gift
    FontAwesome.Git
    FontAwesome.GitSquare
    FontAwesome.GitHub
    FontAwesome.GitHubAlt
    FontAwesome.GithubSquare
    FontAwesome.Gittip
    FontAwesome.Glass
    FontAwesome.Globe
    FontAwesome.Google
    FontAwesome.GooglePlus
    FontAwesome.GooglePlusSquare
    FontAwesome.GraduationCap
    FontAwesome.Group
    FontAwesome.HSquare
    FontAwesome.HackerNews
    FontAwesome.HandODown
    FontAwesome.HandOLeft
    FontAwesome.HandORight
    FontAwesome.HandOUp
    FontAwesome.HddO
    FontAwesome.Header
    FontAwesome.Headphones
    FontAwesome.Heart
    FontAwesome.HeartO
    FontAwesome.History
    FontAwesome.Home
    FontAwesome.HospitalO
    FontAwesome.HTML5
    FontAwesome.Image
    FontAwesome.Inbox
    FontAwesome.Indent
    FontAwesome.Info
    FontAwesome.InfoCircle
    FontAwesome.INR
    FontAwesome.Instagram
    FontAwesome.Institution
    FontAwesome.Italic
    FontAwesome.Joomla
    FontAwesome.JPY
    FontAwesome.Jsfiddle
    FontAwesome.Key
    FontAwesome.KeyboardO
    FontAwesome.KRW
    FontAwesome.Language
    FontAwesome.Laptop
    FontAwesome.Leaf
    FontAwesome.Legal
    FontAwesome.LemonO
    FontAwesome.LevelDown
    FontAwesome.LevelUp
    FontAwesome.LifeBouy
    FontAwesome.LifeRing
    FontAwesome.LifeSaver
    FontAwesome.LightbulbO
    FontAwesome.Link
    FontAwesome.Linkedin
    FontAwesome.LinkedInSquare
    FontAwesome.Linux
    FontAwesome.List
    FontAwesome.ListAlt
    FontAwesome.ListOl
    FontAwesome.ListUl
    FontAwesome.LocationArrow
    FontAwesome.Lock
    FontAwesome.LongArrowDown
    FontAwesome.LongArrowLeft
    FontAwesome.LongArrowRight
    FontAwesome.LongArrowUp
    FontAwesome.Magic
    FontAwesome.Magnet
    FontAwesome.MailForward
    FontAwesome.MailReply
    FontAwesome.MailReplyAll
    FontAwesome.Male
    FontAwesome.MapMarker
    FontAwesome.Maxcdn
    FontAwesome.Medkit
    FontAwesome.MehO
    FontAwesome.Microphone
    FontAwesome.MicrophoneSlash
    FontAwesome.Minus
    FontAwesome.MinusCircle
    FontAwesome.MinusSquare
    FontAwesome.MinusSquareO
    FontAwesome.Mobile
    FontAwesome.MobilePhone
    FontAwesome.Money
    FontAwesome.MoonO
    FontAwesome.MortarBoard
    FontAwesome.Music
    FontAwesome.Navicon
    FontAwesome.Openid
    FontAwesome.Outdent
    FontAwesome.Pagelines
    FontAwesome.PaperPlane
    FontAwesome.PaperPlaneO
    FontAwesome.Paperclip
    FontAwesome.Paragraph
    FontAwesome.Paste
    FontAwesome.Pause
    FontAwesome.Paw
    FontAwesome.Pencil
    FontAwesome.PencilSquare
    FontAwesome.PencilSquareO
    FontAwesome.Phone
    FontAwesome.PhoneSquare
    FontAwesome.Photo
    FontAwesome.PictureO
    FontAwesome.PiedPiper
    FontAwesome.PiedPiperAlt
    FontAwesome.PiedPiperSquare
    FontAwesome.Pinterest
    FontAwesome.PinterestSquare
    FontAwesome.Plane
    FontAwesome.Play
    FontAwesome.PlayCircle
    FontAwesome.PlayCircleO
    FontAwesome.Plus
    FontAwesome.PlusCircle
    FontAwesome.PlusSquare
    FontAwesome.PlusSquareO
    FontAwesome.PowerOff
    FontAwesome.Print
    FontAwesome.PuzzlePiece
    FontAwesome.Qq
    FontAwesome.Qrcode
    FontAwesome.Question
    FontAwesome.QuestionCircle
    FontAwesome.QuoteLeft
    FontAwesome.QuoteRight
    FontAwesome.Ra
    FontAwesome.Random
    FontAwesome.Rebel
    FontAwesome.Recycle
    FontAwesome.Reddit
    FontAwesome.RedditSquare
    FontAwesome.Refresh
    FontAwesome.Renren
    FontAwesome.Reorder
    FontAwesome.Repeat
    FontAwesome.Reply
    FontAwesome.ReplyAll
    FontAwesome.Retweet
    FontAwesome.Rmb
    FontAwesome.Road
    FontAwesome.Rocket
    FontAwesome.RotateLeft
    FontAwesome.RotateRight
    FontAwesome.Rouble
    FontAwesome.RSS
    FontAwesome.RssSquare
    FontAwesome.RUB
    FontAwesome.Ruble
    FontAwesome.Rupee
    FontAwesome.Save
    FontAwesome.Scissors
    FontAwesome.Search
    FontAwesome.SearchMinus
    FontAwesome.SearchPlus
    FontAwesome.Send
    FontAwesome.SendO
    FontAwesome.Share
    FontAwesome.ShareAlt
    FontAwesome.ShareAltSquare
    FontAwesome.ShareSquare
    FontAwesome.ShareSquareO
    FontAwesome.Shield
    FontAwesome.ShoppingCart
    FontAwesome.SignIn
    FontAwesome.SignOut
    FontAwesome.Signal
    FontAwesome.Sitemap
    FontAwesome.Skype
    FontAwesome.Slack
    FontAwesome.Sliders
    FontAwesome.SmileO
    FontAwesome.Sort
    FontAwesome.SortAlphaAsc
    FontAwesome.SortAlphaDesc
    FontAwesome.SortAmountAsc
    FontAwesome.SortAmountDesc
    FontAwesome.SortAsc
    FontAwesome.SortDesc
    FontAwesome.SortDown
    FontAwesome.SortNumericAsc
    FontAwesome.SortNumericDesc
    FontAwesome.SortUp
    FontAwesome.Soundcloud
    FontAwesome.SpaceShuttle
    FontAwesome.Spinner
    FontAwesome.Spoon
    FontAwesome.Spotify
    FontAwesome.Square
    FontAwesome.SquareO
    FontAwesome.StackExchange
    FontAwesome.StackOverflow
    FontAwesome.Star
    FontAwesome.StarHalf
    FontAwesome.StarHalfEmpty
    FontAwesome.StarHalfFull
    FontAwesome.StarHalfO
    FontAwesome.StarO
    FontAwesome.Steam
    FontAwesome.SteamSquare
    FontAwesome.StepBackward
    FontAwesome.StepForward
    FontAwesome.Stethoscope
    FontAwesome.Stop
    FontAwesome.Strikethrough
    FontAwesome.Stumbleupon
    FontAwesome.StumbleuponCircle
    FontAwesome.Subscript
    FontAwesome.Suitcase
    FontAwesome.SunO
    FontAwesome.Superscript
    FontAwesome.Support
    FontAwesome.Table
    FontAwesome.Tablet
    FontAwesome.Tachometer
    FontAwesome.Tag
    FontAwesome.Tags
    FontAwesome.Tasks
    FontAwesome.Taxi
    FontAwesome.TencentWeibo
    FontAwesome.Terminal
    FontAwesome.TextHeight
    FontAwesome.TextWidth
    FontAwesome.Th
    FontAwesome.ThLarge
    FontAwesome.ThList
    FontAwesome.ThumbTack
    FontAwesome.ThumbsDown
    FontAwesome.ThumbsODown
    FontAwesome.ThumbsOUp
    FontAwesome.ThumbsUp
    FontAwesome.Ticket
    FontAwesome.Times
    FontAwesome.TimesCircle
    FontAwesome.TimesCircleO
    FontAwesome.Tint
    FontAwesome.ToggleDown
    FontAwesome.ToggleLeft
    FontAwesome.ToggleRight
    FontAwesome.ToggleUp
    FontAwesome.TrashO
    FontAwesome.Tree
    FontAwesome.Trello
    FontAwesome.Trophy
    FontAwesome.Truck
    FontAwesome.TRY
    FontAwesome.Tumblr
    FontAwesome.TumblrSquare
    FontAwesome.TurkishLira
    FontAwesome.Twitter
    FontAwesome.TwitterSquare
    FontAwesome.Umbrella
    FontAwesome.Underline
    FontAwesome.Undo
    FontAwesome.University
    FontAwesome.Unlink
    FontAwesome.Unlock
    FontAwesome.UnlockAlt
    FontAwesome.Unsorted
    FontAwesome.Upload
    FontAwesome.USD
    FontAwesome.User
    FontAwesome.UserMd
    FontAwesome.Users
    FontAwesome.VideoCamera
    FontAwesome.VimeoSquare
    FontAwesome.Vine
    FontAwesome.VK
    FontAwesome.VolumeDown
    FontAwesome.VolumeOff
    FontAwesome.VolumeUp
    FontAwesome.Warning
    FontAwesome.Wechat
    FontAwesome.Weibo
    FontAwesome.Weixin
    FontAwesome.Wheelchair
    FontAwesome.Windows
    FontAwesome.Won
    FontAwesome.Wordpress
    FontAwesome.Wrench
    FontAwesome.Xing
    FontAwesome.XingSquare
    FontAwesome.Yahoo
    FontAwesome.Yen
    FontAwesome.Youtube
    FontAwesome.YoutubePlay
    FontAwesome.YoutubeSquare
  }

}
